gotemplate provides a Go library and executable, that executes templates,
using the text/template package from the Go standard library.

One of the advantages of using Go templates,
is that you can incorporate custom Go code
in the template.  This is done by adding a FuncMap to the template.

This package defines a single "file" function as an example.
The library does not add it automatically to the templates, but the main executable does.

The main executable also serves as an example about how to add custom functions to the templates:

{{template "file.tpl" "main/gotemplate.go"}}

This README.md was generated by running the script:

{{template "file.tpl" "readme.sh"}}

Using the following templates:

{{template "file.tpl" "doc/file.tpl"}}

**doc/readme.tpl**

(content not included)


